# Generated by Django 4.2 on 2023-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0005_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
